### ISSUE TITLE
[question] measuring time to first byte?

### ISSUE THREAD

**Issue by lukehsiao** [BalterLoadTesting/balter#10]
With the rise of APIs that use server-sent events (SSE) like ChatGPT, it is becoming more and more common to want to load test and measure time-to-first-byte (TTFB).

For example, TTFB can be a proxy for time-to-first-token (TTFT).

https://www.databricks.com/blog/llm-inference-performance-engineering-best-practices

> Our team uses four key metrics for LLM serving:
>
> 1. **Time To First Token (TTFT)**: How quickly users start seeing the model's output after entering their query. Low waiting times for a response are essential in real-time interactions, but less important in offline workloads. This metric is driven by the time required to process the prompt and then generate the first output token.

Can Balter measure this? If not, is there any interest in supporting this metric?

**Comment by byronwasti** [comment]
Good question! Balter is designed to be agnostic to the actual transaction taking place, so whether or not Balter is able to measure TTFB is largely a factor of what library is being used to make the request. For instance, Reqwest seems to [support TTFB via just not querying the text](https://github.com/seanmonstar/reqwest/issues/1327).

So, using Reqwest as an example, to get TTFB would be using the following in the `#[transaction]`:
```rust
#[transaction] 
async fn foo(client: &reqwest::Client) -> Result<Response, ()> {
     let res = client.post("...")
             .send()
             .await;

     // Don't call `.json()` or `.text()` on the res, instead return immediately to get
     // latency timing on first byte
     res
}
```


Supporting both TTFB _and_ the overall latency of the request might require some additional work in Balter, since right now you would need to choose between one or the other.

**Comment by lukehsiao** [comment]
Very nifty! That satisfies my question, I'll go ahead and close this :).
