### ISSUE TITLE
Reached Goal TPS

### ISSUE THREAD

**Issue by chrisbll971** [BalterLoadTesting/balter#8]
Hello,

I was wondering if there is a way to force it to send at a specific TPS? We noticed that it if we set it to 50 TPS it might cap out at 35 TPS and say it’s unable to reach the goal TPS.

Thanks,
Chris

**Comment by byronwasti** [comment]
Hi Chris,

Setting to `.tps()` will force to a specific TPS. However, it will limit itself if it is unable to reach the TPS requested. For instance, if spinning up more concurrent tasks isn't increasing the TPS due to a bottleneck in the network or CPU, then it will stop spinning up more tasks as that is increasing the amount of contention.

I haven't done a ton of performance analysis of Balter recently, so if the numbers are looking way too low let me know -- I can try to dig in and see if I accidentally introduced a performance regression recently. Still working on getting automated benchmarking set up for everything!

**Comment by byronwasti** [comment]
I wrote a bit more about this on the site: https://www.balterloadtesting.com/guide/#tps-limited

35 TPS does seem absurdly low. Doing some light benchmarking Balter should be able to easily exceed 20,000 TPS on a single machine. Do you mind sharing a bit about what your setup is like?

**Comment by chrisbll971** [comment]
Ok awesome. Interestingly, the guide page is appearing as a 404 not found on my end.

This specific API we are load testing is slower (200-300 ms average latency) and seemed increasing the TPS would cap out at around 35 TPS and was curious if there was some way to ignore the guardrails of limiting the rate based on contention.

I can confirm with our lower latency APIs I was able to send at over 5,000 TPS quite easily.

**Comment by byronwasti** [comment]
Sorry about that! I changed around the website structure a bit, correct link is https://www.balterloadtesting.com/balter/guide/#tps-limited

Thanks for the additional details, let me test some things on my side and see if I can reproduce and find where the bottleneck is. I would like to add advanced configuration parameter support (one of which is removing guardrails), but I'm not entirely sure that will help the situation. Essentially, Balter determines if the TPS is flat-lining/going down, and removing the guardrails will likely make the situation worse.

If you have a chance, do you mind letting me know what the concurrency Balter reports for that Scenario is? I've found Tokio starts to have a bit of trouble at ~2,000 concurrent tasks all waiting on the network.

**Comment by chrisbll971** [comment]
Awesome, thanks. Currently, if I run the benchmark in a single terminal I receive the following output:

`Goal TPS exceeds capability of this server. Found best task count: (7, 14.720314033366046).`

However, if I start the process in multiple terminals I'm able to get up to 35-45 TPS.

**Comment by byronwasti** [comment]
I've added support for testing with noise [0], but unfortunately I'm at a loss for recreating this. If you have a chance to get the trace-level output from Balter (and being on 0.5.2) I should be able to dig into this a bit more. Otherwise I'll continue hunting down whats going on and adding more thorough testing of various components.

[0] https://github.com/BalterLoadTesting/balter/commit/4ea157588ae837c48035c29799957cb893077143

**Comment by chrisbll971** [comment]
Wow, that was fast. I will give it a shot tomorrow
